### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by jasonhis** [pywavefront/PyWavefront#97]
I am trying to open this obj file
https://sketchfab.com/3d-models/hoa-hakananaia-752e69d34933438d8230ac829d22300e

Getting this error:

```
Traceback (most recent call last):
    scene = pywavefront.Wavefront('/Users/sixer/Downloads/hoa-hakananaia/source/2738963_2014916101619/mesh/sculpt.obj')
  File "/usr/local/lib/python3.7/site-packages/pywavefront/wavefront.py", line 78, in __init__
    cache=cache)
  File "/usr/local/lib/python3.7/site-packages/pywavefront/obj.py", line 81, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/pywavefront/obj.py", line 91, in parse
    super(ObjParser, self).parse()
  File "/usr/local/lib/python3.7/site-packages/pywavefront/parser.py", line 136, in parse
    self.dispatcher.get(self.values[0], self.parse_fallback)()
  File "/usr/local/lib/python3.7/site-packages/pywavefront/obj.py", line 273, in parse_f
    self.material.vertices += list(consumed_vertices)
  File "/usr/local/lib/python3.7/site-packages/pywavefront/obj.py", line 381, in consume_faces
    t_index = (int(parts[1]) - 1) if has_vt else None
ValueError: invalid literal for int() with base 10: ''
```

**Comment by einarf** [comment]
Looks like it's related to inconsistent vertex format were uv index is not present suddenly.

```
f 3174/2356/3174 2424/2331/2424 3933/1543/3933 
f 4090//4090 3273//3273 29//29 
```

**Comment by einarf** [comment]
I'll try to introduce a fix to this very soon.

**Comment by einarf** [comment]
Bugfix works in 9b1754a works and the model renders perfectly fine. 
<img width="1392" alt="Screenshot 2019-06-10 at 20 21 26" src="https://user-images.githubusercontent.com/5418180/59217052-66b92400-8bbd-11e9-9ba0-5d5ffb4eebac.png">

**Comment by einarf** [comment]
1.0.4 released
